version: '3.8'

services:
  hello-dalle-discordbot:
    image: heavygee/hello-dalle-discordbot:latest
    environment:
      # These should be populated from your .env file locally, or GitHub secrets in CI/CD
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BOTSPAM_CHANNEL_ID=${BOTSPAM_CHANNEL_ID}
      - PROFILE_CHANNEL_ID=${PROFILE_CHANNEL_ID}
      - WELCOME_CHANNEL_ID=${WELCOME_CHANNEL_ID}
      - WELCOME_PROMPT=${WELCOME_PROMPT}
    restart: unless-stopped 