# This file is used ONLY for GitHub Actions testing
# Production deployment uses: /home/heavygee/docker/apps/hello-dalle/docker-compose.prod.yml
# DO NOT use this file for production deployment

version: '3.8'

name: hello-dalle-test

services:
  hello-dalle-discordbot-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    container_name: hello-dalle-discordbot-test
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN:-test-token}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-test-key}
      - BOTSPAM_CHANNEL_ID=${BOTSPAM_CHANNEL_ID:-123456789}
      - WELCOME_CHANNEL_ID=${WELCOME_CHANNEL_ID:-123456789}
      - PROFILE_CHANNEL_ID=${PROFILE_CHANNEL_ID:-123456789}
      - BOT_USER_ROLE=${BOT_USER_ROLE:-123456789}
      - WELCOME_PROMPT=${WELCOME_PROMPT:-test prompt}
      - GENDER_SENSITIVITY=${GENDER_SENSITIVITY:-false}
      - STEALTH_WELCOME=${STEALTH_WELCOME:-false}
      - WILDCARD=${WILDCARD:-0}
      - DEBUG=${DEBUG:-false}
      - NODE_ENV=test
    volumes:
      # Minimal volumes for testing
      - ./data:/usr/src/app/data
      - ./logs:/usr/src/app/logs
    command: npm test
    profiles:
      - test
