version: '3.8'

name: hello-dalle-dev

services:
  hello-dalle-discordbot:
    build:
      context: .
    container_name: hello-dalle-dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Exclude node_modules from host mount
    environment:
      # These should be populated from your .env file locally
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BOTSPAM_CHANNEL_ID=${BOTSPAM_CHANNEL_ID}
      - PROFILE_CHANNEL_ID=${PROFILE_CHANNEL_ID}
      - WELCOME_CHANNEL_ID=${WELCOME_CHANNEL_ID}
      - WELCOME_PROMPT=${WELCOME_PROMPT}
    command: npm run start:dev # Assuming you'll add a start:dev script in package.json for nodemon/ts-node
    restart: unless-stopped 