name: Docker Build and Push to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create version.txt for test build
        run: echo "test-version" > version.txt
      - name: Run tests
        run: |
          npm install
          npm run build
          npm test 